### ISSUE TITLE
Вводящий в заблужение программный интерфейс для ads1112

### ISSUE THREAD

**Issue by 14droplets** [cansat-rsce/librscs#48]
в функциях `rscs_ads1115_start_single` и `rscs_ads1115_start_continuous` следует добавить параметр - идентификатор измеряемого канала. Функцию `rscs_ads1115_set_channel` при этом следует убрать.

Иначе возникает соблазн запустить `rscs_ads1115_start_continous` и затем вызовами `rscs_ads1115_set_channel` и `rscs_ads1115_read` получать значения.

Уже есть жертвы!

Так же было бы прикольно сделать функцию, которая бы устанавливала канал, запускала бы одиночное измерение и возвращала бы результ. Все в одном флаконе, разумеется с указанием измеряемого канала. Практика показывает что это очень часто востребованная операция.

**Comment by Kirs67** [comment]
Ок, делаю

> Так же было бы прикольно сделать функцию, которая бы устанавливала канал, запускала бы одиночное измерение и возвращала бы результ

как назвать?

**Comment by 14droplets** [comment]
Закрыто в #49
