### ISSUE TITLE
Преобразование значений ускорения ADXL 345 в физические величины выглядит странно

### ISSUE THREAD

**Issue by 14droplets** [cansat-rsce/librscs#51]
функция `rscs_adxl345_cast_to_G` не похожа на правильную

**Comment by Kirs67** [comment]
Нет, с ней как раз-таки всё нормально. Мы выставляем FULL_RES, поэтому у нас везде максимальное разрешение - 4 mg/lsb. Проблемы на нестандартных настройках были вызваны ГРУБЕЙШИМИ ошибками в функциях установки параметров. (Похоже, никто до этого их вдумчиво не читал) Правлю.

**Comment by 14droplets** [comment]
Ой вей, я тоже ничего не заметил

**Comment by Kirs67** [comment]
Поправил, завтра протестчу

**Comment by 14droplets** [comment]
Закрыто в #53
