### ISSUE TITLE
Возможна ошибка в считывании сырых значений

### ISSUE THREAD

**Issue by Agnus290** [cansat-rsce/librscs#74]
Макросы регистров:
https://github.com/cansat-rsce/librscs/blob/d5907d65a9e92790ef04719ba3df0328925c129b/rscs/_source/tsl2561.c#L33

Место, которое меня смущает:
https://github.com/cansat-rsce/librscs/blob/d5907d65a9e92790ef04719ba3df0328925c129b/rscs/_source/tsl2561.c#L150
https://github.com/cansat-rsce/librscs/blob/d5907d65a9e92790ef04719ba3df0328925c129b/rscs/_source/tsl2561.c#L153
https://github.com/cansat-rsce/librscs/blob/d5907d65a9e92790ef04719ba3df0328925c129b/rscs/_source/tsl2561.c#L160
https://github.com/cansat-rsce/librscs/blob/d5907d65a9e92790ef04719ba3df0328925c129b/rscs/_source/tsl2561.c#L163

#define DATA0LOW_REG_ADDR 0x0C
#define DATA0HIGH_REG_ADDR 0x0Drscs_e error = rscs_tsl2561_setup(s1);
#define DATA1LOW_REG_ADDR 0x0E
#define DATA1HIGH_REG_ADDR 0x0F

0x0C и 0x0E - адреса младших разрядов

Как я понимаю, функция rscs_i2c_read(sensor_data0, 2, true) (rscs_i2c_read(sensor_data1, 2, true)) Запишет в старший разряд значение 0x0C (0x0E), а затем в младщий значение 0x0D (0x0F)

**Comment by 14droplets** [comment]
Я не понял замечания. А как должно быть?

**Comment by Agnus290** [comment]
Я разобралась

**Comment by 14droplets** [comment]
Неа, так не пойдет. Это не наша личная переписка. Напиши пжлст в чем именно разобралась, чтобы в будущем те, у кого возникнут такие же вопросы, могли бы найти это ишью и почитать

**Comment by Agnus290** [comment]
ОК.
Указатель указывает на младший разряд, и функция соответственно получив первое значение пишет в младший и т.д. по порядку
